from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 610)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 781, 211))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 270, 781, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 230, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 230, 321, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.CNinput = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.CNinput.setGeometry(QtCore.QRect(20, 170, 171, 41))
        self.CNinput.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        icon = QtGui.QIcon.fromTheme("input-tablet")
        self.CNinput.setIcon(icon)
        self.CNinput.setObjectName("CNinput")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(260, 530, 441, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Type_yuor_api = QtWidgets.QLabel(parent=self.centralwidget)
        self.Type_yuor_api.setGeometry(QtCore.QRect(70, 530, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Type_yuor_api.setFont(font)
        self.Type_yuor_api.setObjectName("Type_yuor_api")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 23))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(parent=self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuChoose = QtWidgets.QMenu(parent=self.menubar)
        self.menuChoose.setObjectName("menuChoose")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTranslate = QtGui.QAction(parent=MainWindow)
        self.actionTranslate.setObjectName("actionTranslate")
        self.actionChatGPT = QtGui.QAction(parent=MainWindow)
        self.actionChatGPT.setObjectName("actionChatGPT")
        self.actionChatGPT_Trans = QtGui.QAction(parent=MainWindow)
        self.actionChatGPT_Trans.setObjectName("actionChatGPT_Trans")
        self.menuMain.addAction(self.actionQuit)
        self.menuChoose.addAction(self.actionTranslate)
        self.menuChoose.addAction(self.actionChatGPT)
        self.menuChoose.addAction(self.actionChatGPT_Trans)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuChoose.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(self.textEdit.clear) # type: ignore
        self.pushButton_2.clicked.connect(self.textBrowser.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Translate"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.CNinput.setText(_translate("MainWindow", "CommandLinkButton"))
        self.Type_yuor_api.setText(_translate("MainWindow", "Type your openai api:"))
        self.api_ok.setText(_translate("MainWindow", "OK"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuChoose.setTitle(_translate("MainWindow", "Choose"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionTranslate.setText(_translate("MainWindow", "Translate"))
        self.actionChatGPT.setText(_translate("MainWindow", "ChatGPT"))
        self.actionChatGPT_Trans.setText(_translate("MainWindow", "ChatGPT-Trans"))
