# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application[Linux]

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Packge the app
      run: |
        pyinstaller -w main.py
        cp config ./dist/main
        cp icon.png ./dist/main
        cp LICENSE ./dist/main
        cp Refresh_Desktopfile.sh ./dist/main
        cp translations_zh.qm ./dist/main
        cd ./dist
        tar -czvf Smartinput.tar.gz ./main
        sha256sum Smartinput.tar.gz > sha256sum.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: Auto_Packge_Smartinput
          path: |
            ./dist/Smartinput.tar.gz
            ./dist/sha256sum.txt
    - name: Auto push to release
      run: |
        gh release create $(cat version) ./dist/Smartinput.tar.gz ./dist/sha256sum.txt -F "$(cat what's_new)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
