# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application[Linux]

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Packge the app
      run: |
        pyinstaller -w main.py
        cp config ./dist/main
        cp icon.png ./dist/main
        cp LICENSE ./dist/main
        cp Refresh_Desktopfile.sh ./dist/main
        cp translations_zh.qm
        tar -czvf Smartinput.tar.gz ./dist/main
        sha256sum Smartinput.tar.gz > sha256sum.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: code-coverage-report
          path: |
            Smartinput.tar.gz
            sha256sum.txt
